CREATE SCHEMA LAHMAN_BASEBALL;



CREATE TABLE LAHMAN_BASEBALL.AllstarFull(playerID VARCHAR, yearID BIGINT, gameNum BIGINT, gameID VARCHAR, teamID VARCHAR, lgID VARCHAR, GP BIGINT, startingPos BIGINT);
CREATE TABLE LAHMAN_BASEBALL.Appearances(yearID BIGINT, teamID VARCHAR, lgID VARCHAR, playerID VARCHAR, G_all BIGINT, GS BIGINT, G_batting BIGINT, G_defense BIGINT, G_p BIGINT, G_c BIGINT, G_1b BIGINT, G_2b BIGINT, G_3b BIGINT, G_ss BIGINT, G_lf BIGINT, G_cf BIGINT, G_rf BIGINT, G_of BIGINT, G_dh BIGINT, G_ph BIGINT, G_pr BIGINT);
CREATE TABLE LAHMAN_BASEBALL.Batting(playerID VARCHAR, yearID BIGINT, stint BIGINT, teamID VARCHAR, lgID VARCHAR, G BIGINT, AB BIGINT, R BIGINT, H BIGINT, "2B" BIGINT, "3B" BIGINT, HR BIGINT, RBI BIGINT, SB BIGINT, CS BIGINT, BB BIGINT, SO BIGINT, IBB BIGINT, HBP BIGINT, SH BIGINT, SF BIGINT, GIDP BIGINT);
CREATE TABLE LAHMAN_BASEBALL.BattingPost(yearID BIGINT, round VARCHAR, playerID VARCHAR, teamID VARCHAR, lgID VARCHAR, G BIGINT, AB BIGINT, R BIGINT, H BIGINT, "2B" BIGINT, "3B" BIGINT, HR BIGINT, RBI BIGINT, SB BIGINT, CS BIGINT, BB BIGINT, SO BIGINT, IBB BIGINT, HBP BIGINT, SH BIGINT, SF BIGINT, GIDP BIGINT);
CREATE TABLE LAHMAN_BASEBALL.Fielding(playerID VARCHAR, yearID BIGINT, stint BIGINT, teamID VARCHAR, lgID VARCHAR, POS VARCHAR, G BIGINT, GS BIGINT, InnOuts BIGINT, PO BIGINT, A BIGINT, E BIGINT, DP BIGINT, PB BIGINT, WP VARCHAR, SB BIGINT, CS BIGINT, ZR VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.FieldingOF(playerID VARCHAR, yearID BIGINT, stint BIGINT, Glf BIGINT, Gcf BIGINT, Grf BIGINT);
CREATE TABLE LAHMAN_BASEBALL.FieldingOFSplit(playerID VARCHAR, yearID BIGINT, stint BIGINT, teamID VARCHAR, lgID VARCHAR, POS VARCHAR, G BIGINT, GS BIGINT, InnOuts BIGINT, PO BIGINT, A BIGINT, E BIGINT, DP BIGINT, PB VARCHAR, WP VARCHAR, SB VARCHAR, CS VARCHAR, ZR VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.FieldingPost(playerID VARCHAR, yearID BIGINT, teamID VARCHAR, lgID VARCHAR, round VARCHAR, POS VARCHAR, G BIGINT, GS BIGINT, InnOuts BIGINT, PO BIGINT, A BIGINT, E BIGINT, DP BIGINT, TP BIGINT, PB BIGINT, SB VARCHAR, CS VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.HomeGames("year.key" BIGINT, "league.key" VARCHAR, "team.key" VARCHAR, "park.key" VARCHAR, "span.first" DATE, "span.last" DATE, games BIGINT, openings BIGINT, attendance BIGINT);
CREATE TABLE LAHMAN_BASEBALL.Managers(playerID VARCHAR, yearID BIGINT, teamID VARCHAR, lgID VARCHAR, inseason BIGINT, G BIGINT, W BIGINT, L BIGINT, rank BIGINT, plyrMgr VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.ManagersHalf(playerID VARCHAR, yearID BIGINT, teamID VARCHAR, lgID VARCHAR, inseason BIGINT, half BIGINT, G BIGINT, W BIGINT, L BIGINT, rank BIGINT);
CREATE TABLE LAHMAN_BASEBALL.Parks("park.key" VARCHAR, "park.name" VARCHAR, "park.alias" VARCHAR, city VARCHAR, state VARCHAR, country VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.People(playerID VARCHAR, birthYear BIGINT, birthMonth BIGINT, birthDay BIGINT, birthCountry VARCHAR, birthState VARCHAR, birthCity VARCHAR, deathYear BIGINT, deathMonth BIGINT, deathDay BIGINT, deathCountry VARCHAR, deathState VARCHAR, deathCity VARCHAR, nameFirst VARCHAR, nameLast VARCHAR, nameGiven VARCHAR, weight BIGINT, height BIGINT, bats VARCHAR, throws VARCHAR, debut DATE, finalGame DATE, retroID VARCHAR, bbrefID VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.Pitching(playerID VARCHAR, yearID BIGINT, stint BIGINT, teamID VARCHAR, lgID VARCHAR, W BIGINT, L BIGINT, G BIGINT, GS BIGINT, CG BIGINT, SHO BIGINT, SV BIGINT, IPouts BIGINT, H BIGINT, ER BIGINT, HR BIGINT, BB BIGINT, SO BIGINT, BAOpp DOUBLE, ERA DOUBLE, IBB BIGINT, WP BIGINT, HBP BIGINT, BK BIGINT, BFP BIGINT, GF BIGINT, R BIGINT, SH BIGINT, SF BIGINT, GIDP BIGINT);
CREATE TABLE LAHMAN_BASEBALL.PitchingPost(playerID VARCHAR, yearID BIGINT, round VARCHAR, teamID VARCHAR, lgID VARCHAR, W BIGINT, L BIGINT, G BIGINT, GS BIGINT, CG BIGINT, SHO BIGINT, SV BIGINT, IPouts BIGINT, H BIGINT, ER BIGINT, HR BIGINT, BB BIGINT, SO BIGINT, BAOpp DOUBLE, ERA DOUBLE, IBB BIGINT, WP BIGINT, HBP BIGINT, BK BIGINT, BFP BIGINT, GF BIGINT, R BIGINT, SH BIGINT, SF BIGINT, GIDP BIGINT);
CREATE TABLE LAHMAN_BASEBALL.SeriesPost(yearID BIGINT, round VARCHAR, teamIDwinner VARCHAR, lgIDwinner VARCHAR, teamIDloser VARCHAR, lgIDloser VARCHAR, wins BIGINT, losses BIGINT, ties BIGINT);
CREATE TABLE LAHMAN_BASEBALL.Teams(yearID BIGINT, lgID VARCHAR, teamID VARCHAR, franchID VARCHAR, divID VARCHAR, Rank BIGINT, G BIGINT, Ghome BIGINT, W BIGINT, L BIGINT, DivWin VARCHAR, WCWin VARCHAR, LgWin VARCHAR, WSWin VARCHAR, R BIGINT, AB BIGINT, H BIGINT, "2B" BIGINT, "3B" BIGINT, HR BIGINT, BB BIGINT, SO BIGINT, SB BIGINT, CS BIGINT, HBP BIGINT, SF BIGINT, RA BIGINT, ER BIGINT, ERA DOUBLE, CG BIGINT, SHO BIGINT, SV BIGINT, IPouts BIGINT, HA BIGINT, HRA BIGINT, BBA BIGINT, SOA BIGINT, E BIGINT, DP BIGINT, FP DOUBLE, "name" VARCHAR, park VARCHAR, attendance BIGINT, BPF BIGINT, PPF BIGINT, teamIDBR VARCHAR, teamIDlahman45 VARCHAR, teamIDretro VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.TeamsFranchises(franchID VARCHAR, franchName VARCHAR, active VARCHAR, NAassoc VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.TeamsHalf(yearID BIGINT, lgID VARCHAR, teamID VARCHAR, Half BIGINT, divID VARCHAR, DivWin VARCHAR, Rank BIGINT, G BIGINT, W BIGINT, L BIGINT);
CREATE TABLE LAHMAN_BASEBALL.AwardsManagers(playerID VARCHAR, awardID VARCHAR, yearID BIGINT, lgID VARCHAR, tie VARCHAR, notes VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.AwardsPlayers(playerID VARCHAR, awardID VARCHAR, yearID BIGINT, lgID VARCHAR, tie VARCHAR, notes VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.AwardsShareManagers(awardID VARCHAR, yearID BIGINT, lgID VARCHAR, playerID VARCHAR, pointsWon BIGINT, pointsMax BIGINT, votesFirst BIGINT);
CREATE TABLE LAHMAN_BASEBALL.AwardsSharePlayers(awardID VARCHAR, yearID BIGINT, lgID VARCHAR, playerID VARCHAR, pointsWon DOUBLE, pointsMax BIGINT, votesFirst DOUBLE);
CREATE TABLE LAHMAN_BASEBALL.CollegePlaying(playerID VARCHAR, schoolID VARCHAR, yearID BIGINT);
CREATE TABLE LAHMAN_BASEBALL.HallOfFame(playerID VARCHAR, yearID BIGINT, votedBy VARCHAR, ballots VARCHAR, needed VARCHAR, votes VARCHAR, inducted VARCHAR, category VARCHAR, needed_note VARCHAR);
CREATE TABLE LAHMAN_BASEBALL.Salaries(yearID BIGINT, teamID VARCHAR, lgID VARCHAR, playerID VARCHAR, salary BIGINT);
CREATE TABLE LAHMAN_BASEBALL.Schools(schoolID VARCHAR, name_full VARCHAR, city VARCHAR, state VARCHAR, country VARCHAR);

CREATE OR REPLACE VIEW LAHMAN_BASEBALL.TEAM_DETAILS AS (

with WS_WINS AS (SELECT COUNT(PS.yearID) AS WS_TITLES,
					T.franchID,
					MAX(PS.yearID) AS LAST_WS_WIN
					FROM LAHMAN_BASEBALL.SeriesPost PS
						JOIN LAHMAN_BASEBALL.Teams T
							on T.teamID = PS.teamIDwinner 
							AND T.yearID = PS.yearID
					WHERE PS.ROUND = 'WS'
					AND PS.yearID >= 1969
					GROUP BY ALL)
					
SELECT  TF.franchName,
		T.franchID, 
		SUM(W) as TOTAL_WIN,
		SUM(L) as TOTAL_LOSS,
		TOTAL_WIN + TOTAL_LOSS AS TOTAL_GAMES,
		MIN(yearID) FIRST_YEAR_PLAYED,
		MAX(yearID) LAST_YEAR_PLAYED,
		round(TOTAL_WIN/TOTAL_GAMES,2) as WIN_RATE,
		WS_WINS.WS_TITLES,
		WS_WINS.LAST_WS_WIN
		FROM LAHMAN_BASEBALL.Teams T
			JOIN LAHMAN_BASEBALL.TeamsFranchises TF
				on T.franchID = TF.franchID 
			LEFT JOIN WS_WINS 
				on WS_WINS.franchID=T.franchID 
		WHERE divID is not null
		GROUP BY ALL
		ORDER BY WIN_RATE DESC)

;



